# Generated by Django 5.2.13 on 2026-04-24 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_batch_capacity_batch_created_at_batch_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingRegistration',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('registration_type', models.CharField(default='online', max_length=20)),
                ('learning_time', models.CharField(default='morning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_registrations', to='batches.batch')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
