# Generated by Django 5.2.13 on 2026-04-24 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('payment_status', models.CharField(default='not_paid', max_length=20)),
                ('tuition_fee', models.PositiveIntegerField(default=12000)),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('employment_status', models.CharField(default='no', max_length=20)),
                ('batch', models.ForeignKey(blank=True, db_column='batch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='batches.batch')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
