# Generated by Django 5.2.13 on 2026-04-24 09:17

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_batch_capacity_batch_created_at_batch_updated_at'),
        ('students', '0001_initial'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_employed', models.BooleanField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-checked_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 24, 9, 17, 10, 284250, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_type',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'In-Person')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['batch'], name='students_st_batch_i_c8b64c_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['payment_status'], name='students_st_payment_09238e_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['employment_status'], name='students_st_employm_1782e0_idx'),
        ),
        migrations.AddField(
            model_name='employmentcheckin',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_checkins', to='students.student'),
        ),
        migrations.AddField(
            model_name='employmentcheckin',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_checkins', to='surveys.survey'),
        ),
    ]
