# Generated by Django 5.2.13 on 2026-05-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_add_telegram_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduation_status',
            field=models.CharField(choices=[('graduated', 'Graduated'), ('not_graduated', 'Not Graduated'), ('dropout', 'Dropout')], default='not_graduated', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_type',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'In-Person'), ('bot', 'Bot')], default='online', max_length=20),
        ),
    ]
