# Generated by Django 5.2.13 on 2026-04-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('survey_type', models.CharField(default='yes_no', max_length=32)),
                ('last_sent', models.DateField()),
                ('response_yes', models.PositiveIntegerField(default=0)),
                ('response_no', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-last_sent', 'id'],
            },
        ),
    ]
