# Generated by Django 5.2.13 on 2026-05-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_seed_default_timeslots'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='computer_course_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='extension_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='mwf_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='office_course_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='tts_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
