# Generated by Django 5.2.13 on 2026-05-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0005_batch_computer_course_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='mwf_capacity',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='tts_capacity',
        ),
        migrations.AddField(
            model_name='batch',
            name='timeslot_1_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='timeslot_2_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='timeslot_3_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='timeslot_4_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='timeslot_5_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
