# Generated by Django 5.2.13 on 2026-05-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0006_remove_batch_mwf_capacity_remove_batch_tts_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
