# Generated by Django 5.2.13 on 2026-05-10 10:06

from django.db import migrations, models


def convert_is_closed_to_status(apps, schema_editor):
	"""Convert is_closed boolean to status CharField."""
	Batch = apps.get_model('batches', 'Batch')
	for batch in Batch.objects.all():
		if batch.is_closed:
			batch.status = 'closed'
		else:
			batch.status = 'open'
		batch.save(update_fields=['status'])


def reverse_convert(apps, schema_editor):
	"""Reverse the conversion (for rollback)."""
	Batch = apps.get_model('batches', 'Batch')
	for batch in Batch.objects.all():
		batch.is_closed = (batch.status == 'closed')
		batch.save(update_fields=['is_closed'])


class Migration(migrations.Migration):

	dependencies = [
		('batches', '0007_batch_is_closed'),
	]

	operations = [
		migrations.AddField(
			model_name='batch',
			name='status',
			field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('completed', 'Completed')], default='open', max_length=20),
		),
		migrations.RunPython(convert_is_closed_to_status, reverse_convert),
		migrations.RemoveField(
			model_name='batch',
			name='is_closed',
		),
	]
